/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calendar;

import java.io.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.swing.*;

/**
 *
 * @author Cosmin
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        this.setTitle("Calendar");
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);  
        file_load();
        update_list();
        this.one.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Eveniment nou");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Editare");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Stergere");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Zilnica", "Saptamanala", "Lunara" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Vizualizare");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    a.setVisible(true);
    a.reinit();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (jList1.getModel().getSize()>0){
        c.remove(l_list.get(jList1.getSelectedIndex()).idGet());
        file_save();
        update_list();
        }    
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        b.op_eSet(c.get(l_list.get(jList1.getSelectedIndex()).idGet()));
        b.idxSet(l_list.get(jList1.getSelectedIndex()).idGet());
        //jButton2.setEnabled(false);
        b.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void update_list(){
        this.l_list.clear();
        int i;
        int j;
        String[] bstrings;
        bstrings=new String[this.c.size()];
        String[] tp={"[ I ]","[O]","[N]"};
        j=0;
        for (i=0;i<this.c.size();i++){
            this.l_list.add(i,this.c.get(i).cod(),this.c.get(i).anget()+"/");
            bstrings[j]=this.c.get(i).ziget()+'/'+this.c.get(i).lunaget()+"/"+this.c.get(i).anget()+" "+tp[Integer.parseInt(c.get(i).tipget())]+" "+this.c.get(i).oraget()+" "+this.c.get(i).titluget();
        j++;
        }
        
        jList1.setModel(new javax.swing.DefaultListModel<String>() {
            String[] strings = bstrings;
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        if (jList1.getModel().getSize()>0){
            jList1.setSelectedIndex(0);
            jButton2.setEnabled(true);
            jButton3.setEnabled(true);
        }else{
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);    
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
               new NewJFrame().setVisible(true);
               
              
                
            }
        });
    }
private  calendar c= new calendar();
private evn a=new evn();
private eve b=new eve();
private Alarm e=new Alarm();
private llist l_list=new llist();
private Thread one = new Thread() {
    private NewJFrame d;
    public void run() {
        int i=0,id;
        DateFormat dateFormat;
        Date date;
        String[] dt;
        String strdata,ccod;
        while (1!=2){
            try {
                

                Thread.sleep(500);
            } catch(InterruptedException v) {
                System.out.println(v);
            }   
            i++;
            if (i==60){i=0;}
         
         // Citire data si ora
            if(i==39){
                dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss"); 	
                date = new Date(); 
                strdata= dateFormat.format(date);
                System.out.println(strdata);
                strdata=strdata.replace(" ",";");
                strdata=strdata.replace("/",";");
                strdata=strdata.replace(":",";");
                dt=strdata.split(";");
                ccod=dt[0]+dt[1]+dt[2]+dt[3]+dt[4];
                id=c.alarm(ccod);
                System.out.println(ccod);
                if (id!=-1){
                    e.a_titluset(c.get(id).titluget());
                    e.a_contset(c.get(id).contget());
                    e.setVisible(true);
                    c.remove(id);
                    update_list();
                    file_save();
                }
            }
            
         // Verificare si adaugare eveniment nou
            if(a.operatorGet()){
                c.add(a.op_eGet().tipget(),a.op_eGet().anget(), a.op_eGet().lunaget(), a.op_eGet().ziget(), a.op_eGet().oraget(), a.op_eGet().titluget(), a.op_eGet().contget());
                a.operatorSet(false);
                System.out.println("Obiect adaugat");
                update_list();
                file_save();
            }
         // Verificare si editare eveniment selectat    
             if(b.operatorGet()){
                c.set(b.idxGet(),b.op_eGet().tipget(),b.op_eGet().anget(), b.op_eGet().lunaget(), b.op_eGet().ziget(), b.op_eGet().oraget(), b.op_eGet().titluget(), b.op_eGet().contget());
                System.out.println(b.idxGet()+b.op_eGet().tipget()+b.op_eGet().anget()+ b.op_eGet().lunaget()+ b.op_eGet().ziget()+ b.op_eGet().oraget()+ b.op_eGet().titluget()+ b.op_eGet().contget());
                b.operatorSet(false);
                System.out.println("Obiect modificat");
                update_list();
                file_save();
            }
        }
        
    }  
};
public void file_load(){
        
        String fileName = "Calendar_db.csv";
        String[] elem;

        String line = null;

        try {

            FileReader fileReader = 
                new FileReader(fileName);


            BufferedReader bufferedReader = 
                new BufferedReader(fileReader);

            while((line = bufferedReader.readLine()) != null) {
               elem=line.split("`");
               c.add(elem[0], elem[1], elem[2], elem[3], elem[4], elem[5], elem[6]);
            }   


            bufferedReader.close();         
        }
        catch(FileNotFoundException ex) {
            System.out.println(
                "Unable to open file '" + 
                fileName + "'");                
        }
        catch(IOException ex) {
            System.out.println(
                "Error reading file '" 
                + fileName + "'");                  

        }
    }
    public void file_save(){
        String fileName = "Calendar_db.csv";
        int i;
        if(c.even.size()>0){
        try {
            
            FileWriter fileWriter =new FileWriter(fileName);

            BufferedWriter bufferedWriter = new BufferedWriter(fileWriter);
            
            for(i=0;i<c.even.size();i++){
            bufferedWriter.write(c.get(i).tipget()+"`"+c.get(i).anget()+"`"+c.get(i).lunaget()+"`"+c.get(i).ziget()+"`"+c.get(i).oraget()+"`"+c.get(i).titluget()+"`"+c.get(i).contget());
            bufferedWriter.newLine();                
            }

            bufferedWriter.close();
        }
        catch(IOException ex) {
            System.out.println(
                "Error writing to file '"
                + fileName + "'");
        }
    }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
